blank_issues_enabled: false
contact_links:
  - name: Frequently Asked Questions
    url: https://github.com/skick1234/DisTube/wiki/Frequently-Asked-Questions
    about: DisTube Frequently Asked Questions
  - name: Discord Support Server
    url: https://discord.gg/feaDd9h
    about: Suggest an idea for this project or ask a question here on Discord
